# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

##
warnings_are_errors: true
sudo: required
bioc_required: true

r_binary_packages:
 - RUnit
 - gap
 - survey

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - BIOC_USE_DEVEL="TRUE"

