# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
bioc_required: true

##
warnings_are_errors: true
sudo: required

r_binary_packages:
 - RUnit
 - gap
 - survey
 - knitr
 - rmarkdown

bioc_packages:
 - BiocGenerics
 - BiocStyle

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - BIOC_USE_DEVEL="FALSE"

